It's because your `enum` is not the standard library `enum` module. You probably have the package [`enum34`][1] installed. 

One way check if this is the case is to inspect the property `enum.__file__`

    import enum
    print(enum.__file__)  
    # standard library location should be something like 
    # /usr/local/lib/python3.6/enum.py

Since python 3.6 the enum34 library is no longer compatible with the standard library. The library is also unnecessary, so you can simply uninstall it.

    pip uninstall -y enum34


If you need the code to run on python versions both <=3.4 and >3.4, you can try having [`enum-compat`][2] as a requirement. It only installs `enum34` for older versions of python without the standard library enum.


  [1]: https://pypi.python.org/pypi/enum34
  [2]: https://pypi.python.org/pypi/enum-compat/0.0.2